//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twist.WinFormUI.Resources.Turkish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Twist_AddProductForm_Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Twist_AddProductForm_Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twist.WinFormUI.Resources.Turkish.Twist.AddProductForm.Turkish", typeof(Twist_AddProductForm_Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Hızlanma:.
        /// </summary>
        internal static string lb_BackAcceleration {
            get {
                return ResourceManager.GetString("lb_BackAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Tur:.
        /// </summary>
        internal static string lb_BackCircuit {
            get {
                return ResourceManager.GetString("lb_BackCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Yavaşlama:.
        /// </summary>
        internal static string lb_BackDeceleration {
            get {
                return ResourceManager.GetString("lb_BackDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Hız:.
        /// </summary>
        internal static string lb_BackSpeed {
            get {
                return ResourceManager.GetString("lb_BackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo 1 Renk:.
        /// </summary>
        internal static string lb_Cable1Color {
            get {
                return ResourceManager.GetString("lb_Cable1Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo 2 Renk:.
        /// </summary>
        internal static string lb_Cable2Color {
            get {
                return ResourceManager.GetString("lb_Cable2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo çapı:.
        /// </summary>
        internal static string lb_CableDiameter {
            get {
                return ResourceManager.GetString("lb_CableDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo yönü:.
        /// </summary>
        internal static string lb_CableDirection {
            get {
                return ResourceManager.GetString("lb_CableDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burulma Sonrasi Boy 1:.
        /// </summary>
        internal static string lb_CableLengthAfterTwisting {
            get {
                return ResourceManager.GetString("lb_CableLengthAfterTwisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burulma Sonrasi Boy 2:.
        /// </summary>
        internal static string lb_CableLengthAfterTwisting2 {
            get {
                return ResourceManager.GetString("lb_CableLengthAfterTwisting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo Bırakma Süresi:.
        /// </summary>
        internal static string lb_CableReleaseDuration {
            get {
                return ResourceManager.GetString("lb_CableReleaseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo Kesiti:.
        /// </summary>
        internal static string lb_CableSection {
            get {
                return ResourceManager.GetString("lb_CableSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Hızlanma:.
        /// </summary>
        internal static string lb_FowardAcceleration {
            get {
                return ResourceManager.GetString("lb_FowardAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Tur:.
        /// </summary>
        internal static string lb_FowardCircuit {
            get {
                return ResourceManager.GetString("lb_FowardCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Yavaşlama:.
        /// </summary>
        internal static string lb_FowardDeceleration {
            get {
                return ResourceManager.GetString("lb_FowardDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Hız:.
        /// </summary>
        internal static string lb_FowardSpeed {
            get {
                return ResourceManager.GetString("lb_FowardSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Adı:.
        /// </summary>
        internal static string lb_LabelName {
            get {
                return ResourceManager.GetString("lb_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatve Boyu:.
        /// </summary>
        internal static string lb_PitchLength {
            get {
                return ResourceManager.GetString("lb_PitchLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı:.
        /// </summary>
        internal static string lb_ProductName {
            get {
                return ResourceManager.GetString("lb_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        internal static string lb_Quantity {
            get {
                return ResourceManager.GetString("lb_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağ Acik Boy:.
        /// </summary>
        internal static string lb_SağAcikBoy {
            get {
                return ResourceManager.GetString("lb_SağAcikBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol Açik Boy:.
        /// </summary>
        internal static string lb_SolAçikBoy {
            get {
                return ResourceManager.GetString("lb_SolAçikBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tur Arası Bekleme:.
        /// </summary>
        internal static string lb_TourInterregnumWaiting {
            get {
                return ResourceManager.GetString("lb_TourInterregnumWaiting", resourceCulture);
            }
        }
    }
}
