//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twist.WinFormUI.Resources.Turkish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Twist_ListProductsForm_Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Twist_ListProductsForm_Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twist.WinFormUI.Resources.Turkish.Twist.ListProductsForm.Turkish", typeof(Twist_ListProductsForm_Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Hızlanma.
        /// </summary>
        internal static string BackAcceleration {
            get {
                return ResourceManager.GetString("BackAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Tur.
        /// </summary>
        internal static string BackCircuit {
            get {
                return ResourceManager.GetString("BackCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Yavaşlama.
        /// </summary>
        internal static string BackDeceleration {
            get {
                return ResourceManager.GetString("BackDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Hız.
        /// </summary>
        internal static string BackSpeed {
            get {
                return ResourceManager.GetString("BackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string btn_Update {
            get {
                return ResourceManager.GetString("btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burulma Sonrasi Boy 1.
        /// </summary>
        internal static string BurulmaSonrasiBoy1 {
            get {
                return ResourceManager.GetString("BurulmaSonrasiBoy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burulma Sonrasi Boy 2.
        /// </summary>
        internal static string BurulmaSonrasiBoy2 {
            get {
                return ResourceManager.GetString("BurulmaSonrasiBoy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo 1 Renk.
        /// </summary>
        internal static string Cable1Color {
            get {
                return ResourceManager.GetString("Cable1Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo 2 Renk.
        /// </summary>
        internal static string Cable2Color {
            get {
                return ResourceManager.GetString("Cable2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo çapı.
        /// </summary>
        internal static string CableDiameter {
            get {
                return ResourceManager.GetString("CableDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo yönü.
        /// </summary>
        internal static string CableDirection {
            get {
                return ResourceManager.GetString("CableDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo Bırakma Süres,.
        /// </summary>
        internal static string CableReleaseDuration {
            get {
                return ResourceManager.GetString("CableReleaseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablo Kesiti.
        /// </summary>
        internal static string CableSection {
            get {
                return ResourceManager.GetString("CableSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Hızlanma.
        /// </summary>
        internal static string FowardAcceleration {
            get {
                return ResourceManager.GetString("FowardAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Tur.
        /// </summary>
        internal static string FowardCircuit {
            get {
                return ResourceManager.GetString("FowardCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Yavaşlama.
        /// </summary>
        internal static string FowardDeceleration {
            get {
                return ResourceManager.GetString("FowardDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Hız.
        /// </summary>
        internal static string FowardSpeed {
            get {
                return ResourceManager.GetString("FowardSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Adı.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatve Boyu.
        /// </summary>
        internal static string PitchLength {
            get {
                return ResourceManager.GetString("PitchLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağ Acik Boy.
        /// </summary>
        internal static string SağAcikBoy {
            get {
                return ResourceManager.GetString("SağAcikBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol Açik Boy.
        /// </summary>
        internal static string SolAçikBoy {
            get {
                return ResourceManager.GetString("SolAçikBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tur Arası Bekleme.
        /// </summary>
        internal static string TourInterregnumWaiting {
            get {
                return ResourceManager.GetString("TourInterregnumWaiting", resourceCulture);
            }
        }
    }
}
